<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-U9882TR" failures="1" tests="1" name="test" time="14.079" errors="0" timestamp="2024-06-19T20:36:54 EEST">
  <testcase classname="Tests.ContactFormTest" name="sendMessageTest" time="3.639">
    <failure type="java.lang.AssertionError" message="expected [Thank you for your message. It has been sent.X] but found [Thank you for your message. It has been sent.]">
      <![CDATA[java.lang.AssertionError: expected [Thank you for your message. It has been sent.X] but found [Thank you for your message. It has been sent.]
at Tests.ContactFormTest.sendMessageTest(ContactFormTest.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- sendMessageTest -->
</testsuite> <!-- test -->
